
services:
  server:
    build:
      context: .
      target: final
    depends_on:
      - sqlserver
    command: sh -c dotnet-ef database update
    ports:
      - 5245:8080

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "u)j&cYOEHoSsmj57"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
    driver: local 

